@echo off
echo Starting Dr. Lahiru's Portfolio & Clinic website...
echo Launching Node/Express Backend on port 5000...
start cmd /k "cd backend && npm run dev"
echo Launching Vite React Frontend on port 5173...
start cmd /k "cd frontend && npm run dev"
echo Both servers launched in separate terminal windows.
pause
